### ISSUE TITLE
Composer cant find the package

### ISSUE THREAD

**Issue by aaroniker** [panique/mini#190]
Hi,
i got the following problem:

I tried to load MINI with composer:

```
{
    "require": {
        "panique/mini": "1.*"
    }
}
```

It's says that there is no package with that name .. any help ? :)

**Comment by panique** [comment]
Yes that's because there was never a 1.x release :)
You'll have to use dev-master (install tutorials says that) ! I know, it's not really professional to use it like this, but that's how it works currently... When there's time then I'll make a proper release.

Litte side-issue: This should be installed like shown in the tutorial, I'm not sure if you can install it by using *require*.

**Comment by aaroniker** [comment]
ah it worked, thanks! i think i skipped that .. :D

**Comment by panique** [comment]
:)
