### ISSUE TITLE
[WILL BE MOVED TO MINI3] PSR-4

### ISSUE THREAD

**Issue by JaoNoctus** [panique/mini#202]
Can I do a pull request to dev, implementing PSR-4 autoload?

I've done it in a repository based on mini,
[phpXablau](https://github.com/JaoNoctus/phpXablau)

**Comment by panique** [comment]
Hey, sure! But please allow some weeks for proper testing, I think there are a lot of changes... I would even thing that it might be better to release this a new fork, as the changes might be too much (you know, when documentations ans tutorials have to be rewritten, then it's too much).

**Comment by JaoNoctus** [comment]
@panique You can test, I did the implementation and also updated the documentation.
7f7f3f1fdcb90f831cff014826460736288fbc1c

**Comment by panique** [comment]
@JaoNoctus Hey, i really really love your PSR-4 version of MINI, but i'm unsure if using this autoloader is the best choice for such a minimal-as-possible-PHP-skeleton! Thing is, lots of beginners will probably see composer and then think "damn, too complicated" !

My idea is this: Let's keep MINI 1 as it is, so that even beginners can use it without having to think about autoloaders, namespaces etc, and let's create MINI 3 (MINI 2 already exists, it's made with Slim framework/router inside) out of your fork! I like the namespace version so much that it's probably the best way to go on with the entire project exactly like you did!

Please gimme some days/weeks to re-organize this project a little bit. If you like i can give you full admin rights for the mini 3 repo too :)

**Comment by panique** [comment]
@JaoNoctus MINI3 is now official, coming up in Q3/2016
![mini3](https://cloud.githubusercontent.com/assets/156321/15448749/619e3dec-1f6a-11e6-98ab-6450ae1d09e5.png)

**Comment by panique** [comment]
@JaoNoctus Big Big Thanks! Canyou please do a pull request to develop branch ?

**Comment by JaoNoctus** [comment]
@panique We can create an organization for the mini, like _"mini-framework"_. What do you think?

**Comment by panique** [comment]
@JaoNoctus that's a good idea, let's collect some names first please: maybe...

- https://github.com/mini is taken by a user named "mini" who has no contact details, so we cannot ask to get this account :)
- https://github.com/php-mini is available
- https://github.com/mini-framework is also available
- https://github.com/php-mini-framework is also available

Names without dashes like phpmini wouldn't be so good as this will be bad for finding stuff via google etc. as far as i know. I think it's better to spend some time finding the best name, as changing it later might create problems for people who are then already using the project (pulling updates is hard when the repo name/path changes). @everybody else please add suggestions for the name, if anybody is reading this :)

**Comment by panique** [comment]
hey @JaoNoctus , I've forked your excellent PSR4 version of mini to https://github.com/panique/mini3 ! plz gimme some time for minor changes and updated auto-installers, i'll then give you full rights over the repo! thanks for the fork!, it's exactly what this project needed!

if more people are interested in this, then i'll for sure transform the entire project to a github organization
